### PR TITLE
Compatibility with PHPUnit 6

### PR DESCRIPTION
**Pull request by Lctrs**

### CODE REVIEW

**Comment by Lctrs** [comment]
@xabbuh a new minor version of php-xapi/serializer with the PHPUnit 6 support should be released to make it pass.

**Comment by xabbuh** [comment]
Can you update the `composer.json` file like in https://github.com/php-xapi/symfony-serializer/pull/6/files#diff-b5d0ee8c97c7abd7e3fa29b9a27d1780R17?

**Comment by Lctrs** [comment]
@xabbuh It's green !

**Comment by xabbuh** [comment]
Thank you @Lctrs.

**Pull request closed without merging**
